---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: chartmuseum-pr-git
  namespace: tenant-a
  labels:
    acm-app: chartmuseum-pr
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: tenant-a-ch-helm/channel
  name: chartmuseum
  packageFilter:
    version: 3.3.0
  placement:
    placementRef:
      name: internal-sut-eastus-tenants
      namespace: tenants
  packageOverrides:
    - packageName: chartmuseum
      packageAlias: chartmuseum-pr
      packageOverrides:
        - path: spec
          value:
            securityContext:
              enabled: false
