---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  namespace: chartmuseum-ns
  name: internal-sut-eastus
spec:
  clusterSelector:
    matchLabels:
      zone: internal-sut-eastus
