---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: chartmuseum-git
  namespace: chartmuseum
  labels:
    acm-app: chartmuseum
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  channel: tenant-a-ch-helm/channel
  name: chartmuseum
  packageFilter:
    version: 3.3.0
  placement:
    placementRef:
      name: cloud-azure
      namespace: tenant
  packageOverrides:
    - packageName: chartmuseum
      packageAlias: chartmuseum
