---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: chartmuseum-git
  namespace: tenant-a
  labels:
    acm-app: chartmuseum
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
    apps.open-cluster-management.io/reconcile-option: replace
spec:
  channel: tenant-a-ch-helm/channel
  name: chartmuseum
  packageFilter:
    version: 3.3.0
  placement:
    placementRef:
      name: internal-sut-eastus
  packageOverrides:
    - packageName: chartmuseum
      packageAlias: chartmuseum
      packageOverrides:
        - path: spec
          value:
            securityContext:
              enabled: false
            replicaCount: 5
